### PR TITLE
Trimmed summary for pages and requests

### PR DESCRIPTION
**Pull request by max-ostapenko**
As discussed in https://github.com/HTTPArchive/data-pipeline/issues/149

Some requirements for legacy tables are blocking this from being merged today.

### CODE REVIEW

**Comment by pmeenan** [comment]
The changes themselves look OK to me but has the legacy tables dependency been eliminated? (don't want to merge until it's actually ready)

**Comment by max-ostapenko** [comment]
Not yet, need to wait.
Should I turn it to draft in the meantime?

**Comment by pmeenan** [comment]
That would probably be safest

**Comment by max-ostapenko** [comment]
related to #18

**Comment by max-ostapenko** [comment]
Resolved in other commits.

**Pull request closed without merging**
