### PR TITLE
Add rank column to all.requests

### PR DESCRIPTION
**Pull request by max-ostapenko**
Required for https://github.com/HTTPArchive/data-pipeline/issues/189

### CODE REVIEW

**Review by pmeenan — APPROVED** [review]
LGTM

**Comment by pmeenan** [comment]
Thanks for doing this.

**Comment by max-ostapenko** [comment]
BTW I wasn't sure what to do with `./schema/build.sh`
I couldn't run it on my machine.

**Comment by pmeenan** [comment]
np. Thanks for letting me know (forgot about that step). I just ran it and pushed the updated py file.

**Pull request merged**
